### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by iuri** [iuri/regressionml#5]
Error running cnn-vgg.py gile

Traceback (most recent call last):
  File "/Users/iuridearaujo/Applications/CIMATEC/feature-extraction-cnn.py", line 2, in <module>
    import tensorflow.contrib.slim as slim
ModuleNotFoundError: No module named 'tensorflow.contrib'
(base) Iuris-MacBook-Pro:CIMATEC iuridearaujo$ python3 feature-extraction-cnn.py 
2023-03-03 14:27:54.936333: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/Users/iuridearaujo/Applications/CIMATEC/feature-extraction-cnn.py", line 6, in <module>
    import constant

**Comment by iuri** [comment]
![Image](https://user-images.githubusercontent.com/630005/222816856-e5b6a4f8-e575-42e3-a8d3-6fb65cfa326b.png)
